### ISSUE TITLE
Definition Cores_Wasted

### ISSUE THREAD

**Issue by henkela** [fasrc/slurmmon#6] opened 2014-09-08 10:48 UTC
Hi again, 
I'm looking through the code because I was wondering about the numbers on cores wasted in the whitespace report. In Node.py (l.89 I think) you define Cores_Wasted as CPUAlloc - CPULoad. As far as I could see CPULoad is the 1min load average from /proc/loadavg and CPUAlloc is the number of cores. 
The naming "Cores wasted" sounds like wasted, unused, non-utilized cores to me, like, for example, somebody calling for a full node with N cores and just using one of the N cores and therefore wasting N-1 cores. 
The more I think about it, I can see why you chose the quantity of CPUAlloc - CPULoad since the difference will approach zero when the cpus are "loaded" enough. Then still the name in the report is misleading somehow. I will add the definition of it to the whitespace report table for now. But I would be interested in your thoughts on this. 
By the way, are GPUs supported already? I think I didn't see anything in the code about it.

**Comment by jabrcx** [comment] 2014-09-09 03:11
Yup, your explanation of `Cores_Wasted` as unused, non-utilized cores and your example of only using 1 of N allocated cores is spot on.  It's exactly why the whitespace report came about: when the cluster is not fully utilized -- when on overall utilization plots there there is a band of white space below the line of total resources and above the stack of used resources -- the people with the money want to know why it's not being put to use and the people with the batch jobs want to know why their jobs are pending.  Jobs asking for more resources than they actually require is one major contributing factor, and the purpose of the whitespace report is to identify those jobs and users.

Could you explain how you find `Cores_Wasted` misleading?  I'm not seeing an opposing, incorrect intepretation in your note.

A couple minor technical notes on the node parameters, in case this is where the issue is:

`CPUAlloc` is the number of cores _allocated to jobs_, not just the static number of cores on the node.

`CPULoad` is actually the instantaneous number of running tasks rather than the 1-min load average:

https://github.com/fasrc/slurmmon/blob/master/lib/python/site-packages/slurmmon/util.py#L95

You're right that this does not account for GPUs yet.  In fact, we use `config.py` to tell the whitespace report to skip our `gpgpu` partition:

https://github.com/fasrc/slurmmon/blob/master/lib/python/site-packages/slurmmon/config.py#L30

**Comment by jabrcx** [comment] 2014-09-09 03:47
Correction about `CPULoad` -- for the whitespace report it's actually taking what scontrol claims:

https://github.com/fasrc/slurmmon/blob/master/lib/python/site-packages/slurmmon/nodes.py#L104

The code I pointed out before is not used anymore.

**Comment by henkela** [comment] 2014-09-09 07:15
Sorry, I looked through slurmctld and found CPULoad extracted from loadavg as load average. Somehow I missed the lines in util.py. Then you’re absolutely right, no misleading definition here: Cores allocated – Cores in use = Cores wasted.
But one question comes to my mind. Consider a node of N cores and M users are assigned to the cores. How do you separate the used cores? /proc/loadavg is global, isn’t it? Which would mean that you can’t tell who is the “bad boy” then but you would rather know the utilization of the node.
To find the user-specific wasting of cores you might need to use ps instead to gain correlation of cores and users  (I will try that…). Or did I miss something else.

When I’ve time I will have a look at GPU (and when I have access to a GPU node) or are you or is somebody working on that already?

**Comment by henkela** [comment] 2014-09-09 07:18
But what scontrol claims is CPULoad as load average, isn’t it?

**Comment by henkela** [comment] 2014-09-09 10:43
I had a look at how to extract the user-specific CPU usage. Using os information, one would get the PID of the user using ps for example and the look in /proc/PID/stat for the utime, stime, and so on as well as the cpu it's running on. Combining this data with information of /proc/stat (the total cpu time) one should get a cpuload per user. 
What I'm not sure of is how to put it into the slurmmon module (and where). I had a look at util.py and was thinking about another definition get_cpu_ps(), which would use the approach mentioned above. But I'm not sure how to provide the user id to this definition. 

For example: 
def get_cpu_ps(user-id):
   PID=util.runsh('ps -u user-id -o pid | head -n 1')  # yields the pid of the slurm_script process 
   cat /proc/[PID]/stat | awk ...
   or 
   [CPULoadPercentage, CPUsAlloc]=pidstat -u -p [PID] | awk '{print $7, $8}'

Probably, there are some easier ways to access it with python. I will have a look at this again later.

**Comment by jabrcx** [comment] 2014-09-12 11:35
Thanks for looking into this and the GPU reporting.  Improvements welcome.

> Consider a node of N cores and M users are assigned to the cores. How do you separate the used cores?

I don't, not for live node state and running jobs.  You can see in the screenshot here:

https://raw.githubusercontent.com/fasrc/slurmmon/master/screenshots/slurmmon_whitespace_report.png

how, in the node report (bottom half), it just lists all the jobs on the nodes, for further narrowing down (by a human).  Often for us, though, it's obvious -- e.g. in that example the top 5 worst nodes had only a single job running on them.  Sometimes it's not any particular bad job, and there is something else wrong with the node (e.g. hung fs or some orphaned proc).

In the job report jobs (the top half), the wall times and cpu times _are_ per-job (both from sacct), so in that case automatic conclusions can be made about individual jobs.  It's also more reliable for identifying actual problem jobs, since it's evaluating successfully completed jobs, where as the instantaneous node state query may catch a job during a lull, a failure, or some other exceptional case.

> When I've time I will have a look at GPU (and when I have access to a GPU node) or are you or is somebody working on that already?

Nobody's working on that as far as I know, so that would be great.

> But what scontrol claims is CPULoad as load average, isn't it?

Yup, some version of it.  I'm not sure if it's 1, 5, 10, runnable tasks, or some other number.  We've also seen significant delays between `/proc/loadavg` and what Slurm reports (I presume because Slurm doesn't want polling to interfere with jobs too much).

> Using os information, one would get the PID of the user using ps for example...

This is an entirely different approach than what the node report is doing now -- it requires executing code on each node.  Currently, there is just one call to `scontrol show node` (fast and easy), which has CPULoad for each node.  I moved away from the code that queries nodes' `/proc` to reduce interference with the running jobs (polling overhead) and also to reduce distributed execution code in slurmmon.

Given the job-level accounting is the better way to identify bad jobs anyways (for the reasons I mentioned above), we've been fine with the node-level accounting providing node-level stats.  Maybe you'll find the same in practice?

The patches you have in mind could be helpful for future features, though...

**Comment by jabrcx** [comment] 2014-09-22 23:03
Small correction -- when I wrote the above, I forgot that the local proc stuff _is_ still used, in the optional `slurmmond-computenode` service for ganglia plots of node allocation vs utilization (different code than for the whitespace report).  It's still node-level stats, though, so it hasn't had the need to tease apart per-user/job stats.  (I think there's some code merging that should go on there, too.)

Anyways, I'm closing this out, but patches for improving this are still welcome.

**Closed as completed by jabrcx** 2014-09-22 23:03 UTC
